"""empty message

Revision ID: 7dac4be0ef94
Revises: 
Create Date: 2020-06-18 13:03:02.953566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dac4be0ef94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('full_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('position', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_position'), 'users', ['position'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('minutes',
    sa.Column('minute_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('name_of_org', sa.String(length=60), nullable=True),
    sa.Column('purpose', sa.String(length=60), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('attendees', sa.String(length=60), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('minute_id')
    )
    op.create_index(op.f('ix_minutes_attendees'), 'minutes', ['attendees'], unique=False)
    op.create_index(op.f('ix_minutes_name_of_org'), 'minutes', ['name_of_org'], unique=False)
    op.create_index(op.f('ix_minutes_purpose'), 'minutes', ['purpose'], unique=False)
    op.create_index(op.f('ix_minutes_title'), 'minutes', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_minutes_title'), table_name='minutes')
    op.drop_index(op.f('ix_minutes_purpose'), table_name='minutes')
    op.drop_index(op.f('ix_minutes_name_of_org'), table_name='minutes')
    op.drop_index(op.f('ix_minutes_attendees'), table_name='minutes')
    op.drop_table('minutes')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_position'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
